import { useCallback, useEffect, useState } from "react";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import CabecalhoPrincipal from "../Components/CabecalhoPrincipal";
import { useAuth } from "../context/AuthProvider";
import { goalsApi } from "../service/Services";

const today = new Date().toISOString().slice(0, 10);
const emptyGoal = { name: "", description: "", targetAmount: "", deadline: today };
const emptyContribution = { amount: "", description: "", contributionDate: today };
const money = (value) => Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

const ViewMetas = () => {
  const { token } = useAuth(); const [goals, setGoals] = useState([]); const [form, setForm] = useState(emptyGoal); const [editingId, setEditingId] = useState(null); const [expanded, setExpanded] = useState(null); const [contributions, setContributions] = useState([]); const [contribution, setContribution] = useState(emptyContribution); const [error, setError] = useState("");
  const load = useCallback(() => goalsApi.list(token).then(setGoals).catch((e) => setError(e.message)), [token]); useEffect(() => { load(); }, [load]);
  const saveGoal = async (e) => { e.preventDefault(); try { const payload = { ...form, targetAmount: Number(form.targetAmount) }; if (editingId) await goalsApi.update(token, editingId, payload); else await goalsApi.create(token, payload); setForm(emptyGoal); setEditingId(null); await load(); } catch (err) { setError(err.message); } };
  const editGoal = (goal) => { setEditingId(goal.id); setForm({ name: goal.name, description: goal.description || "", targetAmount: goal.targetAmount, deadline: goal.deadline }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const deleteGoal = async (id) => { if (!window.confirm("Excluir a meta e todos os seus aportes?")) return; try { await goalsApi.delete(token, id); if (expanded === id) setExpanded(null); await load(); } catch (e) { setError(e.message); } };
  const openContributions = async (goalId) => { if (expanded === goalId) { setExpanded(null); return; } setExpanded(goalId); try { setContributions(await goalsApi.listContributions(token, goalId)); } catch (e) { setError(e.message); } };
  const addContribution = async (e) => { e.preventDefault(); try { await goalsApi.createContribution(token, expanded, { ...contribution, amount: Number(contribution.amount) }); setContribution(emptyContribution); setContributions(await goalsApi.listContributions(token, expanded)); await load(); } catch (err) { setError(err.message); } };
  const deleteContribution = async (id) => { if (!window.confirm("Excluir este aporte?")) return; try { await goalsApi.deleteContribution(token, expanded, id); setContributions(await goalsApi.listContributions(token, expanded)); await load(); } catch (e) { setError(e.message); } };
  return <><CabecalhoPrincipal /><main className="app-shell p-6 md:p-10"><div className="max-w-6xl mx-auto"><p className="eyebrow">Planejamento</p><h1 className="text-4xl font-black mb-8">Metas financeiras</h1>
    <Form onSubmit={saveGoal} className="surface-card p-6 mb-8"><h2 className="text-2xl font-black mb-5">{editingId ? "Editar meta" : "Nova meta"}</h2><div className="grid md:grid-cols-4 gap-4"><Form.Group><Form.Label>Nome</Form.Label><Form.Control required maxLength={120} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Form.Group><Form.Group><Form.Label>Valor objetivo</Form.Label><Form.Control required type="number" min="0.01" step="0.01" value={form.targetAmount} onChange={(e) => setForm({ ...form, targetAmount: e.target.value })} /></Form.Group><Form.Group><Form.Label>Prazo</Form.Label><Form.Control required type="date" min={today} value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} /></Form.Group><div className="flex gap-2 items-end"><Button type="submit" variant="success">{editingId ? "Salvar" : "Criar meta"}</Button>{editingId && <Button variant="outline-secondary" onClick={() => { setEditingId(null); setForm(emptyGoal); }}>Cancelar</Button>}</div><Form.Group className="md:col-span-4"><Form.Label>Descrição</Form.Label><Form.Control maxLength={255} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Form.Group></div>{error && <div className="alert alert-danger mt-4 mb-0">{error}</div>}</Form>
    <div className="grid lg:grid-cols-2 gap-6">{goals.map((goal) => <article className="surface-card p-6" key={goal.id}><div className="flex justify-between gap-4"><div><h2 className="text-2xl font-black mb-1">{goal.name}</h2><p className="text-secondary">{goal.description}</p></div><strong>{Number(goal.progressPercentage).toFixed(1)}%</strong></div><div className="progress-track mb-2"><span style={{ width: `${Math.min(100, Number(goal.progressPercentage))}%` }} /></div><div className="goal-stats"><span>Acumulado<strong>{money(goal.currentAmount)}</strong></span><span>Falta<strong>{money(goal.remainingAmount)}</strong></span><span>Por mês<strong>{money(goal.monthlyRequiredSavings)}</strong></span></div><p className="text-sm mt-4">Prazo: {new Date(`${goal.deadline}T12:00:00`).toLocaleDateString("pt-BR")}</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="success" onClick={() => openContributions(goal.id)}>{expanded === goal.id ? "Fechar aportes" : "Aportes"}</Button><Button size="sm" variant="outline-primary" onClick={() => editGoal(goal)}>Editar</Button><Button size="sm" variant="outline-danger" onClick={() => deleteGoal(goal.id)}>Excluir</Button></div>
      {expanded === goal.id && <div className="contributions-panel"><Form onSubmit={addContribution} className="grid sm:grid-cols-2 gap-3 mb-4"><Form.Control required type="number" min="0.01" step="0.01" placeholder="Valor" value={contribution.amount} onChange={(e) => setContribution({ ...contribution, amount: e.target.value })} /><Form.Control required type="date" value={contribution.contributionDate} onChange={(e) => setContribution({ ...contribution, contributionDate: e.target.value })} /><Form.Control maxLength={150} placeholder="Descrição do aporte" value={contribution.description} onChange={(e) => setContribution({ ...contribution, description: e.target.value })} /><Button type="submit" size="sm">Registrar aporte</Button></Form>{contributions.map((item) => <div className="list-row" key={item.id}><div><strong>{money(item.amount)}</strong><small>{item.description || "Aporte"} · {new Date(`${item.contributionDate}T12:00:00`).toLocaleDateString("pt-BR")}</small></div><Button size="sm" variant="outline-danger" onClick={() => deleteContribution(item.id)}>Excluir</Button></div>)}{!contributions.length && <small>Nenhum aporte nesta meta.</small>}</div>}
    </article>)}</div>{!goals.length && <div className="surface-card p-8 empty-state">Nenhuma meta cadastrada.</div>}
    {!!goals.length && <section className="surface-card p-6 mt-6"><h2 className="text-2xl font-black mb-4">Acompanhamento mensal</h2>{goals.map((goal) => <div className="monthly-goal" key={`monthly-${goal.id}`}><strong>{goal.name}</strong><div className="monthly-summary"><div><small>Meta mensal</small><strong>{money(goal.monthlyTargetAmount)}</strong></div><div><small>Aportado no mês</small><strong>{money(goal.currentMonthContributed)}</strong></div><div><small>Falta neste mês</small><strong>{money(goal.currentMonthRemaining)}</strong></div><div className={Number(goal.currentMonthExtra) > 0 ? "is-extra" : ""}><small>Extra no mês</small><strong>{money(goal.currentMonthExtra)}</strong></div><div className={Number(goal.overdueAmount) > 0 ? "is-overdue" : ""}><small>Em atraso</small><strong>{money(goal.overdueAmount)}</strong></div></div></div>)}</section>}
  </div></main></>;
};
export default ViewMetas;
